
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int tk_Izquierda = 62;
  public static final int tk_Borde = 69;
  public static final int tk_Columna_A2 = 44;
  public static final int menos = 3;
  public static final int tk_TextoB_C = 52;
  public static final int tk_TextoB_A = 36;
  public static final int tk_TextoA_C = 51;
  public static final int tk_TextoA_A = 35;
  public static final int punto = 21;
  public static final int tk_SetContenido = 84;
  public static final int TextoN = 20;
  public static final int tk_GetAncho = 76;
  public static final int tk_CrearTabla = 88;
  public static final int tk_Boton_C = 54;
  public static final int tk_GetContenido = 82;
  public static final int tk_ColumnaC_A2 = 43;
  public static final int tk_Boton_A = 38;
  public static final int tk_Derecha = 63;
  public static final int tk_True = 98;
  public static final int divicion = 5;
  public static final int tk_Cuerpo_C = 48;
  public static final int mas = 2;
  public static final int cadena = 113;
  public static final int tk_Repetir = 72;
  public static final int tk_Cuerpo_A = 32;
  public static final int tk_Espacio_C = 49;
  public static final int menorigual = 26;
  public static final int tk_Insertar = 73;
  public static final int tk_Espacio_A = 33;
  public static final int menorq = 19;
  public static final int decimal = 111;
  public static final int tk_Else = 71;
  public static final int tk_Echo = 102;
  public static final int mayorq = 18;
  public static final int tk_SetAlineacion = 85;
  public static final int tk_Cabecera_C = 46;
  public static final int tk_Cabecera_A = 30;
  public static final int tk_Fondo = 94;
  public static final int tk_Azul = 104;
  public static final int tk_SetTexto = 92;
  public static final int tk_Rosado = 109;
  public static final int tk_ClickBoton = 93;
  public static final int mayorigual = 25;
  public static final int tk_GetAlineacion = 83;
  public static final int id = 112;
  public static final int tk_Fila_C = 56;
  public static final int tk_Negro = 107;
  public static final int tk_Fila_A = 40;
  public static final int tk_Tabla_C = 55;
  public static final int tk_Texto = 97;
  public static final int tk_Tabla_A = 39;
  public static final int tk_Compi_C = 45;
  public static final int tk_Compi_A = 29;
  public static final int tk_SetPath = 78;
  public static final int tk_If = 70;
  public static final int tk_HS_C = 101;
  public static final int llaveC = 10;
  public static final int tk_HS_A = 100;
  public static final int llaveA = 9;
  public static final int tk_CrearImagen = 74;
  public static final int exclama = 22;
  public static final int tk_Parrafo_C = 50;
  public static final int tk_Alineacion = 95;
  public static final int tk_Parrafo_A = 34;
  public static final int tk_Centrado = 64;
  public static final int tk_CrearTextoB = 87;
  public static final int tk_CrearTextoA = 86;
  public static final int EOF = 0;
  public static final int tk_False = 99;
  public static final int tk_Justificado = 65;
  public static final int tk_Amarillo = 108;
  public static final int Eti_Coment = 114;
  public static final int parentC = 8;
  public static final int tk_GetPath = 75;
  public static final int tk_Columna_C2 = 60;
  public static final int parentA = 7;
  public static final int numero = 110;
  public static final int tk_Gris = 106;
  public static final int tk_GetTexto = 91;
  public static final int tk_Imagen_C = 53;
  public static final int tk_Imagen_A = 37;
  public static final int dosPts = 15;
  public static final int tk_ID = 96;
  public static final int OR = 24;
  public static final int tk_Path = 66;
  public static final int error = 1;
  public static final int corecheC = 12;
  public static final int corecheA = 11;
  public static final int tk_SetAlto = 80;
  public static final int diferente = 28;
  public static final int puntComa = 16;
  public static final int tk_CrearBoton = 90;
  public static final int interrC = 14;
  public static final int tk_SetAncho = 79;
  public static final int interrA = 13;
  public static final int tk_ColumnaC_C2 = 59;
  public static final int igualigual = 27;
  public static final int por = 4;
  public static final int tk_SetBorde = 89;
  public static final int coma = 17;
  public static final int tk_GetAlto = 77;
  public static final int igual = 6;
  public static final int tk_CrearParrafo = 81;
  public static final int tk_ColumnaC_C = 57;
  public static final int AND = 23;
  public static final int tk_Rojo = 103;
  public static final int tk_Columna_C = 58;
  public static final int tk_Ancho = 68;
  public static final int tk_ColumnaC_A = 41;
  public static final int tk_Columna_A = 42;
  public static final int tk_Titulo_C = 47;
  public static final int tk_Alto = 67;
  public static final int tk_Titulo_A = 31;
  public static final int tk_Verde = 105;
  public static final int tk_Salto = 61;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "mas",
  "menos",
  "por",
  "divicion",
  "igual",
  "parentA",
  "parentC",
  "llaveA",
  "llaveC",
  "corecheA",
  "corecheC",
  "interrA",
  "interrC",
  "dosPts",
  "puntComa",
  "coma",
  "mayorq",
  "menorq",
  "TextoN",
  "punto",
  "exclama",
  "AND",
  "OR",
  "mayorigual",
  "menorigual",
  "igualigual",
  "diferente",
  "tk_Compi_A",
  "tk_Cabecera_A",
  "tk_Titulo_A",
  "tk_Cuerpo_A",
  "tk_Espacio_A",
  "tk_Parrafo_A",
  "tk_TextoA_A",
  "tk_TextoB_A",
  "tk_Imagen_A",
  "tk_Boton_A",
  "tk_Tabla_A",
  "tk_Fila_A",
  "tk_ColumnaC_A",
  "tk_Columna_A",
  "tk_ColumnaC_A2",
  "tk_Columna_A2",
  "tk_Compi_C",
  "tk_Cabecera_C",
  "tk_Titulo_C",
  "tk_Cuerpo_C",
  "tk_Espacio_C",
  "tk_Parrafo_C",
  "tk_TextoA_C",
  "tk_TextoB_C",
  "tk_Imagen_C",
  "tk_Boton_C",
  "tk_Tabla_C",
  "tk_Fila_C",
  "tk_ColumnaC_C",
  "tk_Columna_C",
  "tk_ColumnaC_C2",
  "tk_Columna_C2",
  "tk_Salto",
  "tk_Izquierda",
  "tk_Derecha",
  "tk_Centrado",
  "tk_Justificado",
  "tk_Path",
  "tk_Alto",
  "tk_Ancho",
  "tk_Borde",
  "tk_If",
  "tk_Else",
  "tk_Repetir",
  "tk_Insertar",
  "tk_CrearImagen",
  "tk_GetPath",
  "tk_GetAncho",
  "tk_GetAlto",
  "tk_SetPath",
  "tk_SetAncho",
  "tk_SetAlto",
  "tk_CrearParrafo",
  "tk_GetContenido",
  "tk_GetAlineacion",
  "tk_SetContenido",
  "tk_SetAlineacion",
  "tk_CrearTextoA",
  "tk_CrearTextoB",
  "tk_CrearTabla",
  "tk_SetBorde",
  "tk_CrearBoton",
  "tk_GetTexto",
  "tk_SetTexto",
  "tk_ClickBoton",
  "tk_Fondo",
  "tk_Alineacion",
  "tk_ID",
  "tk_Texto",
  "tk_True",
  "tk_False",
  "tk_HS_A",
  "tk_HS_C",
  "tk_Echo",
  "tk_Rojo",
  "tk_Azul",
  "tk_Verde",
  "tk_Gris",
  "tk_Negro",
  "tk_Amarillo",
  "tk_Rosado",
  "numero",
  "decimal",
  "id",
  "cadena",
  "Eti_Coment"
  };
}

