
package Main;

import java.util.ArrayList;
import javax.swing.JTextField;
import javax.swing.GroupLayout;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import Analizadores.*;
import Lista.*;
import java.awt.Desktop;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.PrintStream;
import java.io.StringReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


public class Principal extends javax.swing.JFrame {
    
    private String ruta_archivo,nombre_pestaña,nombre_archivo;
    public ArrayList<JTextArea> ArraytxtArea = new ArrayList<JTextArea>();
    ArrayList<String> ArrayNombrePestaña = new ArrayList<String>();
    int conta = 0;
    Archivos archiv = new Archivos();
    boolean compilado = false;

    public Principal() {
        initComponents();
    }
    
    public void Crear_Pestaña(String texto, int opcion){
        conta++;
        if (opcion == 1)
            {
                nombre_pestaña = "Edicion " + (tPanel1.countComponents());
            }
            else
            {
                nombre_pestaña = archiv.Nombre_Archivo();
            }
        ArrayNombrePestaña.add(nombre_pestaña);
        
        JPanel pan = new JPanel();
        JScrollPane scrol = new JScrollPane();
        JTextArea txt = new JTextArea("ID" + conta);
        txt.setText(texto);
        ArraytxtArea.add(txt);
         
        GroupLayout Mipanel = new GroupLayout(pan);
        
        scrol.setViewportView(txt);
        
        pan.setLayout(Mipanel);
        Mipanel.setHorizontalGroup(
            Mipanel.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(Mipanel.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrol, GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
                .addContainerGap())
        );
        Mipanel.setVerticalGroup(
            Mipanel.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(Mipanel.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrol, GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                .addContainerGap())
        );

        tPanel1.addTab(nombre_pestaña, pan);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        tPanel1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        cbOpciones = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        tPanel3 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtTexto_Plano = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        tPanel2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtConsola = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mNuevoArchivo = new javax.swing.JMenuItem();
        mAbrir = new javax.swing.JMenuItem();
        mGuardar = new javax.swing.JMenuItem();
        mGuardarC = new javax.swing.JMenuItem();
        mCompilar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbOpciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pagina Web Resultante", "Reporte de Tokens", "Errores Lexicos", "Errores Sintacticos" }));
        cbOpciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbOpcionesActionPerformed(evt);
            }
        });

        jButton1.setText("Abrir con Navegador");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtTexto_Plano.setColumns(20);
        txtTexto_Plano.setRows(5);
        jScrollPane2.setViewportView(txtTexto_Plano);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 783, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        );

        tPanel3.addTab("Texto Plano", jPanel5);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 783, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        tPanel3.addTab("Vista HTML", jPanel6);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tPanel3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cbOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(cbOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(tPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        tPanel1.addTab("Resultados", jPanel2);

        txtConsola.setColumns(20);
        txtConsola.setRows(5);
        jScrollPane1.setViewportView(txtConsola);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        tPanel2.addTab("Consola", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 812, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 122, Short.MAX_VALUE)
        );

        tPanel2.addTab("Variables", jPanel4);

        jMenu1.setText("Archivo");

        mNuevoArchivo.setText("Nuevo Archivo");
        mNuevoArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mNuevoArchivoActionPerformed(evt);
            }
        });
        jMenu1.add(mNuevoArchivo);

        mAbrir.setText("Abrir");
        mAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mAbrirActionPerformed(evt);
            }
        });
        jMenu1.add(mAbrir);

        mGuardar.setText("Guardar");
        mGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mGuardarActionPerformed(evt);
            }
        });
        jMenu1.add(mGuardar);

        mGuardarC.setText("Guardar como");
        mGuardarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mGuardarCActionPerformed(evt);
            }
        });
        jMenu1.add(mGuardarC);

        mCompilar.setText("Compilar");
        mCompilar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCompilarActionPerformed(evt);
            }
        });
        jMenu1.add(mCompilar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ayuda");

        jMenuItem6.setText("Manual de Usuario");
        jMenu2.add(jMenuItem6);

        jMenuItem7.setText("Manual Tecnico");
        jMenu2.add(jMenuItem7);

        jMenuItem8.setText("Acerca de");
        jMenu2.add(jMenuItem8);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tPanel1)
                    .addComponent(tPanel2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tPanel2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mCompilarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mCompilarActionPerformed
        //int a = tPanel1.getSelectedIndex();
       // System.out.println("La pestaña " + tPanel1.getTitleAt(a) + " contiene: " + ArraytxtArea.get(a-1).getText());
       
       Listas.limpiar();
       
       try{
           int a = tPanel1.getSelectedIndex();
           String contenido = ArraytxtArea.get(a-1).getText();
           A_Lexico lexico = new A_Lexico(new BufferedReader(new StringReader(contenido)));
           A_Sintactico sintactico = new A_Sintactico(lexico);
           
           try{
                sintactico.parse();
            }catch(Exception e){
            }
           
       }catch(Exception ex){
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    
       String a = Objetos.Informacion.documento;
       System.out.println();
       System.out.println();
       System.out.println(a);
       
    
       try{
                
                FileOutputStream arch = null;
                
                arch = new FileOutputStream(System.getProperty("user.dir")+"\\Pagina.html");
                PrintStream imprimir = new PrintStream(arch);
                
                imprimir.println(Objetos.Informacion.documento);
                imprimir.close();
                
            }catch(FileNotFoundException e){
            }
       
       /*
       System.out.println();
       System.out.println();
       System.out.println("--------- Variables ----------");
       Listas.imprimir();
       System.out.println();
       System.out.println();
       System.out.println("--------- Errores Lexicos ----------");
       Listas.imprimir_E_Lexicos();
       System.out.println();
       System.out.println();
       System.out.println("--------- Errores Sintacticos ----------");
       Listas.imprimir_E_Sintacticos();
       */
       System.out.println();
       System.out.println();
       System.out.println("--------- Variables ----------");
       Listas.imprimir_Variables();
       Listas.Echo();
       txtConsola.setText(Listas.Mi_consola);
       compilado = true;
            
         
    }//GEN-LAST:event_mCompilarActionPerformed

    private void mNuevoArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mNuevoArchivoActionPerformed
        Crear_Pestaña("",1);
        Archivos a = new Archivos();
        tPanel1.setSelectedIndex(ArraytxtArea.size());
    }//GEN-LAST:event_mNuevoArchivoActionPerformed

    private void mAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mAbrirActionPerformed
        Crear_Pestaña(archiv.Abrir(this),2);
        tPanel1.setSelectedIndex(ArraytxtArea.size());
    }//GEN-LAST:event_mAbrirActionPerformed

    private void mGuardarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mGuardarCActionPerformed
        archiv.Guardar_Como(this, ArraytxtArea.get(tPanel1.getSelectedIndex()-1).getText());
    }//GEN-LAST:event_mGuardarCActionPerformed

    private void mGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mGuardarActionPerformed
       archiv.Guardar(ArraytxtArea.get(tPanel1.getSelectedIndex()-1).getText());
    }//GEN-LAST:event_mGuardarActionPerformed

    private void cbOpcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbOpcionesActionPerformed
        if(compilado){
            switch(cbOpciones.getSelectedIndex()){
                case 0:
                    Listas.ver_HTML();
                    txtTexto_Plano.setText(Listas.contHTML);
                    break;

                case 1:            
                    try {
                        Listas.Reporte_Tokens();
                    } catch (FileNotFoundException ex) {
                        Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    txtTexto_Plano.setText(Listas.contTokens);
                    break;

                case 2:
                    try {
                        Listas.Reporte_E_Lexicos();
                    } catch (FileNotFoundException ex) {
                        Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    txtTexto_Plano.setText(Listas.contE_Lex);
                    break;

                case 3:
                    try {
                        Listas.Reporte_E_Sintacticos();
                    } catch (FileNotFoundException ex) {
                        Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    txtTexto_Plano.setText(Listas.contE_Sin);
                    break;

            }
        }else{
            JOptionPane.showMessageDialog(this,"NO HA COMPILADO NINGUN ARCHIVO","ERROR!",JOptionPane.ERROR_MESSAGE);
        }
        
        //txtTexto_Plano.setText(cbOpciones.getSelectedItem().toString());
    }//GEN-LAST:event_cbOpcionesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         if(compilado){
            switch(cbOpciones.getSelectedIndex()){
                case 0:
                    break;

                case 1:            
                    try {
                        Listas.Reporte_Tokens();
                        File imagen = new File(System.getProperty("user.dir")+"\\Reporte_Tokens.html");
                        try {
                            Thread.sleep(1000);
                        } catch (InterruptedException ex) {
                            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        Desktop.getDesktop().open(imagen);
                    } catch (FileNotFoundException ex) {
                        Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (IOException ex) {
                    Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    break;

                case 2:
                    try {
                        Listas.Reporte_E_Lexicos();
                        File imagen = new File(System.getProperty("user.dir")+"\\Reporte_Errores_Lex.html");
                        try {
                            Thread.sleep(1000);
                        } catch (InterruptedException ex) {
                            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                        }
                            Desktop.getDesktop().open(imagen);
                        } catch (FileNotFoundException ex) {
                            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (IOException ex) {
                        Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    break;

                case 3:
                    try {
                        Listas.Reporte_E_Sintacticos();
                        File imagen = new File(System.getProperty("user.dir")+"\\Reporte_Errores_Sin.html");
                        try {
                            Thread.sleep(1000);
                        } catch (InterruptedException ex) {
                            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                        }
                            Desktop.getDesktop().open(imagen);
                        } catch (FileNotFoundException ex) {
                            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (IOException ex) {
                        Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    break;

            }
        }else{
            JOptionPane.showMessageDialog(this,"NO HA COMPILADO NINGUN ARCHIVO","ERROR!",JOptionPane.ERROR_MESSAGE);
        }
            
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbOpciones;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JMenuItem mAbrir;
    private javax.swing.JMenuItem mCompilar;
    private javax.swing.JMenuItem mGuardar;
    private javax.swing.JMenuItem mGuardarC;
    private javax.swing.JMenuItem mNuevoArchivo;
    private javax.swing.JTabbedPane tPanel1;
    private javax.swing.JTabbedPane tPanel2;
    private javax.swing.JTabbedPane tPanel3;
    private javax.swing.JTextArea txtConsola;
    private javax.swing.JTextArea txtTexto_Plano;
    // End of variables declaration//GEN-END:variables
}
